# Generated by Django 5.1.1 on 2024-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('h', 'высокий'), ('n', 'средний'), ('l', 'низкий'), ('q', 'уже вчера')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('o', 'поставлено'), ('r', 'дорабатывается'), ('p', 'приостановлена'), ('w', 'выполняется'), ('f', 'выполнена'), ('x', 'отменена')], default='o', max_length=1),
        ),
    ]
